[package]
name = "qr-lan"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "qr-lan"
path = "src/main.rs"

[dependencies]
axum   = "0.8"
tokio  = { version = "1", features = ["rt-multi-thread", "macros", "net"] }
serde  = { version = "1", features = ["derive"] }
qrcode = { version = "0.14", default-features = false, features = ["svg"] }
url    = "2"

[profile.release]
strip = true
lto = true
