# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "❯" symbol in the prompt with "➜"
[character]      # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"

[kubernetes]
disabled = true

[nodejs]
symbol = "⬡ "

[battery]
disabled = true
